
name: Build

on:
  push:
    tags: [ "**" ]

env:
  MOD_NAME: "Modding API"
  DLL_NAME: "ModdingAPI"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Build Project
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.MOD_NAME }} v${{ github.ref_name }}

    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: publish/${{ env.DLL_NAME }}.zip
        asset_name: ${{ env.DLL_NAME }}.zip
        asset_content_type: application/zip

    - name: Upload Nuget
      run: dotnet nuget push **\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json